### ISSUE TITLE
Configuring Rtorrent over https is erroring out

### ISSUE THREAD

**Issue by jayjoshi64** [autobrr/autobrr#1595] opened 2024-07-18 07:55 UTC
**Version**
latest: 
```
ghcr.io/autobrr/autobrr                      latest     4bfb8b29a879   4 weeks ago     58MB
```

**Describe the bug**
I am trying to add RuTorrent as a download client.  I have provided the full path, correct credentials but the test is erroring out. 
I feel it may be because it's a remote machine with https connection. 

I am getting the following error
```
client connection test error 
error="error logging into client: https://moser.myseedbox.site/rutorrent/plugins/httprpc/action.php: 
system.hostname XMLRPC call failed: not the required token 
[required <params>, found <body>]"= 
module=download_client stack=[
{"func":"(*service).testRTorrentConnection","line":"169","source":"connection.go"},
{"func":"(*service).testConnection","line":"39","source":"connection.go"},
{"func":"(*service).Test","line":"131","source":"service.go"},
{"func":"downloadClientHandler.test","line":"83","source":"download_client.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"(*Mux).routeHTTP","line":"459","source":"mux.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"(*Mux).ServeHTTP","line":"73","source":"mux.go"},
{"func":"(*Mux).Mount.func1","line":"327","source":"mux.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"Server.IsAuthenticated-fm.Server.IsAuthenticated.func1","line":"85","source":"middleware.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"(*ChainHandler).ServeHTTP","line":"31","source":"chain.go"},
{"func":"(*Mux).routeHTTP","line":"459","source":"mux.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"(*Mux).ServeHTTP","line":"73","source":"mux.go"},
{"func":"(*Mux).Mount.func1","line":"327","source":"mux.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"(*Mux).routeHTTP","line":"459","source":"mux.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"(*Cors).Handler-fm.(*Cors).Handler.func1","line":"289","source":"cors.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"Server.Handler.LoggerMiddleware.func3.1","line":"131","source":"middleware.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"Recoverer.func1","line":"45","source":"recoverer.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"RealIP.func1","line":"36","source":"realip.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"RequestID.func1","line":"76","source":"request_id.go"},
{"func":"HandlerFunc.ServeHTTP","line":"2166","source":"server.go"},
{"func":"(*Mux).ServeHTTP","line":"90","source":"mux.go"}
]

```

**To Reproduce**
1. Select RuTorrent as the download client type. 
2. URL:  (dummy). https://masked.myseedbox/rutorrent/plugins/httprpc/action.php
3. Add credentials 
4. Enable TLS (also tried without TLS)

**Expected behavior**
The connection should work. the test should pass

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser edge, chrome

**Comment by zze0s** [comment] 2024-07-20 10:46
After some debugging this turned out to be because of the host (evoseedbox) uses Digest Auth and not Basic Auth.

We have an issue for Digest Auth https://github.com/autobrr/autobrr/issues/571

A PR #1596 was started to get this working.

I'm closing this since it's a dupe of #571

**Closed by zze0s** 2024-07-20 10:46 UTC
Labels: bug, Download Client: rtorrent
