### ISSUE TITLE
Unable to delete/remove download clients (SQL - no rows in result set)

### ISSUE THREAD

**Issue by Gliese-667** [autobrr/autobrr#1007] opened 2023-07-02 14:21 UTC
**Version**
    1.27.1

**Describe the bug**
Unable to remove old/unused download clients. When I try to remove them via the Edit page, an error pops up:

`Error {"message":"error deleting download client: 1: error executing query: sql: no rows in result set"}`

**To Reproduce**
1. Navigate to Clients settings page.
2. Click Edit on existing client.
3. Click the red Remove button at the bottom of the edit panel.
4. Confirm the removal of the client.
5. Error pops up on top right of the page.

**Expected behavior**
The client should be removed after confirming the removal.

**Screenshots**
![image](https://github.com/autobrr/autobrr/assets/73650479/49e307e2-d3fc-47ca-ba30-c572e4c46ea6)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 22631.1906
 - Browser: Firefox
 - Version: 114.0.2 (64-bit)

**Comment by zze0s** [comment] 2023-07-02 14:23
Dupe of https://github.com/autobrr/autobrr/issues/973 but this yours is better described :+1:

**Comment by Gliese-667** [comment] 2023-07-02 14:57
> Dupe of #973 but this yours is better described 👍

Oops sorry, I even saw that issue when I searched and didn't put two and two together that it was the same problem 🤦 hope this helps either way!

**Comment by zze0s** [comment] 2023-07-21 17:06
@Gliese-667 I can't replicate this. 

* Is this with SQLite or Postgres? All the default setups use SQLite and Postgres requires a bit more setup.
* Do you have multiple clients added?
* Have you been running autobrr for a long time so you started on an early version?

**Comment by Gliese-667** [comment] 2023-07-21 17:26
> * Is this with SQLite or Postgres? All the default setups use SQLite and Postgres requires a bit more setup.
SQLite in that case, it’s basically a fresh install. Probably less than a week old when I originally opened an issue. 
> 
> * Do you have multiple clients added?
Yes, two that I can’t delete and one that is functional. 
> 
> * Have you been running autobrr for a long time so you started on an early version?
Nope, fairly fresh install, here’s the info:

Version:
1.27.1
Commit:
ecc84f5f2d2f66c6044a237edc607946ac62b7b8
Build date:
2023-06-15T21:28:45Z

**Comment by zze0s** [comment] 2023-07-21 17:33
It only happens when the client is not connected to any actions. And I tested with fully setup clients in actions, so it did not hit the issue :smile: 

Have a fix in place so will get it up into next release!

**Comment by Gliese-667** [comment] 2023-07-21 17:53
> It only happens when the client is not connected to any actions. And I tested with fully setup clients in actions, so it did not hit the issue :smile: 
> 
> 
> 
> Have a fix in place so will get it up into next release!

Makes sense. That did fix it - I created a dummy filter and added the client to it and then deleted the client. Thanks for following up!! 🙂

**Closed** 2023-07-21 18:17 UTC
Labels: bug
