### ISSUE TITLE
When using Radarr/Sonarr as a client, no seed time is set for the torrent in qbittorrent.

### ISSUE THREAD

**Issue by strausmann** [autobrr/autobrr#1533] opened 2024-05-03 11:23 UTC
**Version**
Docker v1.41.0

**Describe the bug**

When using autobrr and radarr/sonarr, the setting for “Seed Time” is not set in the qBittorrent client. In radarr/sonarr, a seed time is set in the download client settings for qBittorrent and is also set correctly for downloads that are sent to qBittorrent.

Only for downloads that are sent from autobrr to radarr/sonarr and then actually continue from the torrent client via the download client settings for qBittorrent, no seed time is set.

**To Reproduce**
1. setting the seed time in radarr/sonarr
2. setting up a sonarr/radarr client in autobrr
3. creating a filter for the clients set up in point 2.
4. wait until autobrr sends a torrent to radarr/sonarr and check the seed time in the qbittorrent client.
5. the torrent has no seed time
6. start the same torrent via sonarr/radarr and check in the qbittorrent client with active seed time setting in the torrent

**Expected behavior**

**Screenshots**
The screenshot shows the seed time option when sending the torrent directly to qbittorrent, which is unfortunately missing in Sonarr/Radarr.
![image](https://github.com/autobrr/autobrr/assets/4519228/bdd633ce-1e0c-4ce5-94e9-fae4f2231b89)

**Additional context**
I had inquired about the seed time settings in autobrr. But then I saw that you can only set these settings if autobrr sends the torrent to qBittorrent itself. I think it makes sense to also allow these settings for the clients radarr/sonarr in autobrr so that you can set them.

**Comment by zze0s** [comment] 2024-05-03 11:27
Dupe of https://github.com/autobrr/autobrr/issues/1344

**Closed** 2024-05-04 10:37 UTC
Labels: actions, client-arr
