### ISSUE TITLE
[FEATURE REQ] Have an option to stop everything once a spacelimit is reached on the hard drive

### ISSUE THREAD

**Issue by gabrielmaster123** [autobrr/autobrr#630] opened 2023-01-08 08:18 UTC
**Is your feature request related to a problem? Please describe.**
When I run Autobrr overnight it can happen that when I wake up my harddrive is full and nothing works. that's why I want to be able to stop autobrr once there are only 300GB of space on the hard drive

**Describe the solution you'd like**
A filter option that scans how much space there is on the harddrive 
**Describe alternatives you've considered**
Nothing on side of autobrr, but on rtorrent could just deny injections once there is a space limit
**Additional context**
nothing

**Comment by zze0s** [comment] 2023-01-08 15:02
This is something that has been planned since the start of this project, but haven't made it's way into it yet because I want a solution that works with remote data etc.

Some clients do expose an endpoint to get free space, but not all do.

There is however a pretty simple solution that has been possible since we added the "external filters" that can run scripts.

## Freespace script

https://discord.com/channels/881212911849209957/938041606232211488/1025118932429963286

Something like this. Create the file somewhere `touch ~/freespace.sh && chmod +x ~/freespace.sh`.

```sh
#!/bin/bash
set -e

reqSpace=100000000 # 100GB
SPACE=`df "$HOME/torrents" | awk 'END{print $4}'`
if [[ $SPACE -le reqSpace ]]
then
  #echo "not enough space"
  #echo "free $SPACE"
  exit 1
fi
#echo "got space"
#echo "free $SPACE"
exit 0
```

Then in the filter use it in **External script** with full path like `/home/USER/freespace.sh` no args and **expect 0**.

Freespace in that is set to 100GB in `$HOME/torrents`, change as you wish. If there is free space it will exit with 0 and filter will take that as an OK. If less than 100GB free it will exit with 1 and then not match the filter and stop there.

Try that as an option until we make something better integrated.

**Comment by zze0s** [comment] 2023-01-08 16:16
Dupe of https://github.com/autobrr/autobrr/issues/452

**Closed by zze0s** 2023-01-08 16:16 UTC
Labels: filters, actions, Feature request

**Comment by gabrielmaster123** [comment] 2023-01-10 18:48
So I tried it, kept the limit at 100gb, out the folder location to the downloads folder, used the script in the filter, still whole folder full when I wake up

**Comment by zze0s** [comment] 2023-01-10 18:51
Run the command manually and see what it outputs. It might not work with all systems and setups but should be pretty general. Change the dir as needed.

`df "$HOME/torrents" | awk 'END{print $4}'`
