### ISSUE TITLE
[FEATURE REQ]Remove Plain Text Passwords from Log

### ISSUE THREAD

**Issue by IONECarter** [autobrr/autobrr#721] opened 2023-02-19 15:18 UTC
**Is your feature request related to a problem? Please describe.**
Would like for the .log file that is generated to mask or scrub plain text passwords that seems to exist for IRC networks that are using SASL_PLAIN authentication. However, also noticing it stores the Channel password in plain text, but somewhat less concerned on that.

**Describe the solution you'd like**
Currently IRC network passwords are shown in clear text, would be great if these could be changed to ***** or {PASSWORD}, etc.

**Describe alternatives you've considered**
Alternative could be not saving log files or providing a log level of OFF, but that defeats purpose of having the logs for troubleshooting.

**Additional context**
N/A

**Comment by zze0s** [comment] 2023-02-24 17:04
Dupe of https://github.com/autobrr/autobrr/issues/134

As for saving plain text passwords except for the login, there would have to be some mechanism to unlock at startup and I think most users would fine that a real pain for those using automated updates with docker, or the app crashes etc.

If you set loglevel to `INFO` it should not log any important values. You can also disable the log in the config.toml by either commenting out the field or setting it to an empty string.

**Closed by zze0s** 2023-02-24 17:04 UTC
Labels: Feature request
