### ISSUE TITLE
[FEATURE REQ] Discord notification option for individual filters

### ISSUE THREAD

**Issue by pinkairfreshener** [autobrr/autobrr#960] opened 2023-05-23 23:14 UTC
Discord notification option for individual filters.

I only want notifications for some filters and not others. Going via settings > webhooks > discord, gives notifications for every filter.

It will also help to have separate bots for separate filters such as one for ebooks, one for movies, one for TV shows etc.

**Comment by zze0s** [comment] 2023-05-24 13:55
Dupe of #602 :smiley:

**Closed by zze0s** 2023-05-24 13:55 UTC
Labels: Feature request
