### ISSUE TITLE
Unable to delete client

### ISSUE THREAD

**Issue by fen0x** [autobrr/autobrr#980] opened 2023-06-10 05:28 UTC
**Version**
Version 1.26.2
Build date: 2023-05-17T17:08:02.514Z
Docker container

**Describe the bug**
Trying to delete a client, I get the error 
Error
{"message":"error deleting download client: 18: error executing query: sql: no rows in result set"} 

**To Reproduce**
1. Go to Settings -> Clients
2. Click on "Edit" in a Client
3. Click on "Remove" and confirm "Remove"

**Expected behavior**
Expected to delete the Client row

**Screenshots**
![image](https://github.com/autobrr/autobrr/assets/1822818/6a899346-7db1-45cb-b9aa-57673fc7dfef)

**Comment by zze0s** [comment] 2023-06-10 09:39
Dupe of #793

**Closed by zze0s** 2023-06-10 09:39 UTC
Labels: bug
