### ISSUE TITLE
Perfect FLAC filter doesn't work on OPS

### ISSUE THREAD

**Issue by KyokoMiki** [autobrr/autobrr#1568] opened 2024-06-02 10:03 UTC
**Version**
v1.42.0

**Describe the bug**

17:41:02 DBG TORRENT: Silverize. – Aruru Haru no Kaisou (或る春の回想) – [2023] [Album] CD/FLAC/Lossless/Cue/Log/100 – doujin,japanese,pop – https://orpheus.network/torrents.php?id=1234658 – https://orpheus.network/torrents.php?id=1234658&torrentid=2694153&action=download channel=#announce module=irc network=irc.orpheus.network nick=hermes
17:41:02 DBG (OPS) for release: Silverize. - Aruru Haru no Kaisou (或る春の回想) [2023] (CD FLAC Lossless) rejections: (wanted: perfect flac. got: [Cue FLAC Lossless Log]) method=CheckFilter module=filter
17:41:02 DBG filter OPS rejected release: wanted: perfect flac. got: [Cue FLAC Lossless Log] filter=OPS indexer=ops module=release release="Silverize. - Aruru Haru no Kaisou (或る春の回想) [2023] (CD FLAC Lossless)"

it's actually CD/FLAC/Lossless/Cue/Log/100 in irc announced, but the filter doesn't work, only recognize it as "Cue FLAC Lossless Log".

**Screenshots**

![image](https://github.com/autobrr/autobrr/assets/161209740/08aa9716-edc5-41d0-9e64-d080d4d516c4)

**Comment by zze0s** [comment] 2024-06-02 10:27
Dupe of #1535

**Closed** 2024-06-02 10:27 UTC
Labels: bug
