### ISSUE TITLE
Minimum Seed Time Formula

### ISSUE THREAD

**Issue by CarlitoGil** [autobrr/autobrr#480] opened 2022-09-26 20:25 UTC
**Is your feature request related to a problem? Please describe.**
PrivateHD, CinemaZ, AvistaZ, etc, use formulas to calculate the minimum seed time.
The formulas are based on the size of the torrent payload and they only announce with RSS, not IRC.
The Generic RSS Indexer currently doesn't read the size of the torrent payload for these sites, it parses the size of the .torrent file, as if it were only a few KB.
Without the correct size, the user cannot create Filters for size ranges that determine the min. seed time, and autobrr could grab a torrent with hundreds of GB.
The user could potentially get a H&R, or would have to forgo complete automation.

**Describe the solution you'd like**
1. The correct detection of the torrent payload size from the RSS feed. 
`>(?:: ?)?(\d+(?:\.\d+)?) ?([GMTKP]i?B)<`
That regex applied to the source of each RSS item will unambiguously capture the size.
Otherwise, this is currently a bug, because autobrr erroneously detects the small size of the .torrent file and users could trash their ratio or get H&Rs.
2. Formula with variables enabled for the `seed time limit` field.

**Describe alternatives you've considered**
Using multiple filters for size ranges, but as I said above, without the correct size it's not possible anyway. It would be better to use a formula.

**Additional context**
When built-in indexers for each tracker's RSS feed are added to autobrr, perhaps a checkbox for that indexer could enable calculating the minimum seed time, and doesn't let it fall below that.

**Comment by CarlitoGil** [comment] 2022-09-27 17:20
Hi!

> I disagree with your solution. It would put too much burden on integrating everything into autobrr (and forcing updates so as not the "break" a certain tracker).

The patterns for each tracker's IRC announcement may be different and they may change and break them whenever they want.
Yet, still those patterns are built into autobrr. Why the double standard for trackers that may only use RSS?

If you mean that the trackers might change the formula, well, yeah. That's why I suggested a way in which the user is responsible to update the formula without having to do coding, just like they would have to update their Radarr or RSS Downloader settings, or any autobrr setting for that matter.

> 1. Instead of parsing the payload size from the RSS feed,

The payload is already being parsed from the RSS feed, but it's still buggy.
I'm just proposing parsing it better to fix its bugs.
Do you mean the current method of parsing size from RSS should be scrapped?

> download the .torrent file, parse it and calculate it's size (a general approach)

The problem with that is that those trackers have daily limits on how many .torrents you can grab: 50 per day, 10 for newbies... while the size is right there in the feed...

There are only so many ways to write storage sizes, and they are pretty standard and easily parsed.

Just as with IRC feeds that don't include the size, downloading the .torrent should be a last resort if the size does not exist in the feed.

This regex pattern matches the size of every RSS feed I know. If y'all give me a sample RSS item from any other tracker I'll be glad to match it.
`(?:\b>:?\s*|;)(\d+(?:\.\d+)?)\s?([KMGTP]i?B)\s*[<;]`

> 2. In case option 1 is troubling, pass enough (RSS-related) data to prefilter scripts and let them take care of it (a specific relativistic approach) [Additionally, maybe ship some prefilter scripts with autobrr to minimize this problem]

Sorry, what do you mean? are you referring to `Filter>External>Script`?
Sure, whichever method gets the job done.

**Comment by stacksmash76** [comment] 2022-09-28 11:25
> The patterns for each tracker's IRC announcement may be different and they may change and break them whenever they want. Yet, still those patterns are built into autobrr. Why the double standard for trackers that may only use RSS?

It's not a double standard. You can use custom definitions to override the default built-ins. Another thing to note is that if an indexer doesn't work -- nothing will happen. If a MSTF is miscalculated -- there is some inherent risk to this.

> If you mean that the trackers might change the formula, well, yeah. That's why I suggested a way in which the user is responsible to update the formula without having to do coding, just like they would have to update their Radarr or RSS Downloader settings, or any autobrr setting for that matter.

And the problem is if autobrr doesn't update soon enough to fix this, users will get the burned. Problem is on some sites the MSTF is based off the user class. So, how do you track the user class? Tie it to the indexer? I assure you that people will forget about it (this is especially a problem when one gets demoted).

We have a lot of people who can't be bothered to read the autobrr.com documentation website, yet come to Discord to ask for help. Ergo, I don't think MSTF deserves "first-class" support from autobrr (e.g. why did I get a HnR?)

That's why I am all for making it a bit harder (but only a slight bit) and less straight-forward to set up, so only those who are responsible enough to read through the text should use it. Something along the lines of: enable custom MSTF folder in the config, and put the MSTFs in said folder in autobrr's home directory. That's one option.

> The payload is already being parsed from the RSS feed, but it's still buggy. I'm just proposing parsing it better to fix its bugs. Do you mean the current method of parsing size from RSS should be scrapped?

Yes, if it's buggy, then it should be fixed.*

> The problem with that is that those trackers have daily limits on how many .torrents you can grab: 50 per day, 10 for newbies... while the size is right there in the feed...

I know, hence option 2 which avoids this.*

> There are only so many ways to write storage sizes, and they are pretty standard and easily parsed.
> 
> Just as with IRC feeds that don't include the size, downloading the .torrent should be a last resort if the size does not exist in the feed.

Again, a bit unrelated to the MSTF which was my main point, but I do agree with you on this one.*

> Sorry, what do you mean? are you referring to `Filter>External>Script`? Sure, whichever method gets the job done.

Yeah, but it would have to be extended a bit, since as of right now prefilter scripts just indicate whether input arguments can indicate something which is "acceptable" or "not" and do not have a way of interacting with internal autobrr queue data. But queue API can be exposed, a unique ID sent down the script and the script can make the necessary request if it needs to.

Generally, I see autobrr as a tool which: monitors, filters, sends to download client. That's it. Filtering here boils down to a simple binary classification task. Determining seed time isn't always a binary task (nor simple), hence my objection to it a "first-class citizen". Plus, some see seed time as "required time", others might see it something akin to rtorrent's ratio groups ("desired MSTF"). Another thing to point is that seed time might be different for uploaders, and some uploaders auto-snatch their downloads.

And if we start offering support to this as a built-in feature, where do we stop?

\* I'll be fair and admit my thoughts were a bit all over the place in the previous comment, since your FR is a bug request + FR all in one and I misunderstood this.

Hopefully this clears things up a bit on my stance regarding MSTF.

**Comment by CarlitoGil** [comment] 2022-09-29 08:58
Hi @stacksmash76 

It seems we're talking about different things.
I'm talking about the USER being able to write a formula instead of an integer in the "SEED TIME LIMIT" field.
For that to happen, first autobrr needs to capture the correct size from the RSS feed.

> If a MSTF is miscalculated -- there is some inherent risk to this.

Yes, just like if the user forgets to enable the freeleech option they could trash their ratio.
For the purpose of this FR, the calculation is the user's responsibility.

> So, how do you track the user class? Tie it to the indexer? I assure you that people will forget about it (this is especially a problem when one gets demoted).

If the user forgets to update a formula after being demoted it's the same thing as forgetting to update the integer for minimum seed time now. User's fault. But they are not to blame for the wrong torrent size.


> Yes, if it's buggy, then it should be fixed.*
> Again, a bit unrelated to the MSTF which was my main point, but I do agree with you on this one.*


How can the torrent size be unrelated to the MSFT for sites that use it to calculate the MSFT?
I'm focusing on the size because no approach will work if the size is not reliable.
I'm just offering another reason to fix it that cannot be accomplished by custom RSS feeds.


I like what you're thinking, It'd be great, but it's beyond the scope of this current request, which is the user being able to use a formula instead of a static number. The "how" doesn't matter to me, I read docs.

> And if we start offering support to this as a built-in feature, where do we stop?

Sir, you seem to be focused on something that I put under "Additional context" after the word "perhaps" as an afterthought.
Under "Describe the solution you'd like" I put on step 2: "Formula with variables enabled for the seed time limit field."

I meant that, in the field that already exists, aside from integers, I would love it if this already awesome app could use variables and do math, so I would be able write something like `(72+({{GB}}*2))*60`.
A typo in the formula is the same to me as a typo in the integer. My problem.

But that can't happen until the size bug is addressed, which is why I put it on step 1.

I thought I was making a reasonable request. I don't know if I wrote it wrong or something.

 
> * I'll be fair and admit my thoughts were a bit all over the place in the previous comment, since your FR is a bug request + FR all in one and I misunderstood this.
> 
> Hopefully this clears things up a bit on my stance regarding MSTF.

I appreciate that.
If you feel that I misunderstood anything, or have been unfair, please feel free to point it out.

Thanks again to everyone that works on this app and the poor souls that have to deal with Discord.

Best regards.

**Closed** 2023-01-23 18:24 UTC
Labels: Feature request
