### ISSUE TITLE
[FEATURE REQ] Filters: Custom max downloads period

### ISSUE THREAD

**Issue by FabianGabor** [autobrr/autobrr#431] opened 2022-08-26 18:05 UTC
Would be nice to be able to set custom time periods for downloads, like cron schedule expressions.

For example: 
- n downloads / x period
- 1 download / every 2 hours

**Comment by zze0s** [comment] 2022-08-27 12:47
Duplicate of https://github.com/autobrr/autobrr/issues/400

**Closed by zze0s** 2022-08-27 12:47 UTC
Labels: filters, Feature request
