### ISSUE TITLE
some IRC bots break after router reconnects

### ISSUE THREAD

**Issue by alpert1** [autobrr/autobrr#1068] opened 2023-08-31 01:49 UTC
**Version**
ghcr.io/autobrr/autobrr:latest

**Description**
Some irc-bots break (aka the network is displayed as unhealthy and no announces are received) after a router reconnect (which also changes my IP-address). They only work again after I manually dis- and re-enable them in Settings> IRC. This happens every night and is quite annoying.

**To Reproduce**
1. have irc-bots for certain private trackers active (e.g. ANT, HDT)
2. wait for a router reconnect (or IP-address change?)
3. check settings> IRC
4. see unhealthy networks

**Expected behavior**
Autobrr should either fix this issue or dis- and re-enable the affected bots by itself. No need to get the user involved.

**Docker container:**
 - ghcr.io/autobrr/autobrr:latest

**Comment by zze0s** [comment] 2023-09-02 08:00
Hi!

The IRC implementation have built in re-connect when it's been disconnected. It's also got a ping/timeout.

The re-connect interval is staggered and doubles each time. It should take care of it by itself.

Are you running the latest version and not just a stale latest tag? Latest atm is v1.28.0 :)

**Comment by alpert1** [comment] 2023-09-02 09:25
Yes:
`org.opencontainers.image.version   v1.28.0`

Actually I've noticed that HDT fixes itself after some time, only ANT doesn't. I'll also ask around in their forum for a solution.

**Comment by zze0s** [comment] 2023-09-02 09:31
Ok so then it does actually do what it should. All IRC networks run different software but sometimes nicks get "ghosted" if the connection breaks like that. It usually is a time based thing. autobrr should handle that as automatically as well but maybe there's something on the network end that we can't do much about.

I'll close this as not a bug then. If you need further support then our Discord community is the best place. You can find a link on the docs in the header.

**Closed by zze0s** 2023-09-02 09:31 UTC
Labels: question

**Comment by alpert1** [comment] 2023-09-14 19:34
Is there a way to do the manual dis- and re-enabling of the bot in Settings> IRC with a script? For context: my Autobrr instance runs within a docker container if that helps.

The problem doesn't seem to affect many users, so I seem to be pretty much on my own in finding a solution... :/
